In [2]:
import numpy as np
import pandas as pd

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.arange(1,32,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.linspace(0,2,5) #linearly spaced

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
np.eye(10, dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [12]:
np.random.rand(3,5) # 0 to 1 uniform distribution

array([[0.66739071, 0.95232181, 0.26745001, 0.57640409, 0.20272476],
       [0.01448556, 0.2900829 , 0.21353964, 0.97207691, 0.44404997],
       [0.16663917, 0.14716737, 0.76876542, 0.2402503 , 0.41379701]])

In [13]:
arr = np.random.randn(2,4)
arr

array([[ 0.10690132, -0.50980405, -1.18269908,  0.61584338],
       [ 1.40684675,  0.85131373, -0.15588956,  1.81275997]])

In [14]:
np.random.randint(2,100)

97

In [15]:
np.random.randint(20,56,100)

array([29, 28, 26, 28, 46, 54, 46, 51, 55, 36, 29, 39, 48, 28, 54, 47, 54,
       42, 43, 33, 29, 51, 22, 23, 29, 20, 43, 51, 23, 55, 20, 42, 37, 49,
       22, 39, 30, 35, 44, 50, 29, 38, 39, 33, 38, 36, 50, 28, 47, 43, 51,
       40, 49, 33, 32, 45, 27, 27, 40, 43, 53, 35, 43, 25, 41, 47, 55, 23,
       22, 32, 23, 54, 24, 55, 26, 37, 52, 33, 31, 37, 52, 21, 35, 38, 32,
       24, 20, 28, 21, 22, 38, 37, 26, 29, 47, 32, 45, 35, 46, 36])

In [16]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
r_arr = np.random.randint(0,100,20)
r_arr

array([ 5, 44, 39, 10, 44, 70, 55, 39,  7, 29,  2, 38, 58, 20,  6, 53, 31,
       42, 90, 96])

In [18]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
a.T


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
a = np.random.rand(2,3)
a

array([[0.15708578, 0.03859332, 0.84797027],
       [0.51724853, 0.19545224, 0.42461933]])

In [21]:
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
sample_array[0]

10

In [23]:
sample_array[2:5]

array([12, 13, 14])

In [24]:
sample_array[1:4] = 100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [26]:
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [32]:
subset_sample_array = sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [33]:
subset_sample_array[:] = 100
subset_sample_array

array([100, 100, 100, 100, 100, 100, 100])

## Two Dimensional Array

In [34]:
sample_matrix = np.array([[1,2,3], 
                          [4,5,6],
                          [7,8,9]])
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
sample_matrix[1,1]

5

In [36]:
sample_matrix[2,:]

array([7, 8, 9])

In [37]:
sample_matrix[2]

array([7, 8, 9])

In [39]:
sample_matrix[:,(2,1)]

array([[3, 2],
       [6, 5],
       [9, 8]])